services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nayaka-web-app
    restart: unless-stopped
    ports:
      # Expose langsung port 701 ke publik
      - "701:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
