services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nayaka-web-app
    restart: unless-stopped
    ports:
      # Expose langsung port 3003 ke publik
      - "3003:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
